#!/usr/bin/env python3
"""Generate REPORT.md from the data so that no number in it can drift from the dataset.
Requires data/verdicts.json (from pipeline/verdicts.py). Cell question text quoted here is
CC BY-NC 4.0, Ada Lovelace Institute (Rincon and Chowdhury 2026)."""
import json, glob, statistics
from collections import Counter, defaultdict
cells={c["id"]:c for c in json.load(open("data/cells.json"))["cells"]}
V=json.load(open("data/verifiability.json"))["cells"]; F=json.load(open("data/evidence_fields.json"))["fields"]
sel=json.load(open("data/selection.json"))
recs={json.load(open(p))["study"]["pmid"]:json.load(open(p)) for p in sorted(glob.glob("data/records/*.json"))}
ver=json.load(open("data/verdicts.json")) if glob.glob("data/verdicts.json") else {"verdicts":{}}
A=[cid for cid,v in V.items() if v["class"]=="A"]
STAGES=["Design","Development","Deployment"]; CL={"A":"A artefact","B":"B record","C":"C attestation"}
L=[]; w=L.append
w("# Report: which cells of the sociotechnical evaluation matrix can be evidenced, and which are evidenced in practice\n")
w("Generated by `pipeline/build_report.py` from the data in this repository. Every number below is computed, not typed.\n")
w("## 1. The partition of the matrix\n")
w("The matrix has 120 question cells: 10 criteria across 4 design columns, 3 development columns and 5 deployment columns. Each cell was assigned one verifiability class.\n")
w("| Stage | A artefact | B record | C attestation | Total |"); w("|---|---|---|---|---|")
tot=Counter()
for s in STAGES:
    c=Counter(V[cid]["class"] for cid in cells if cells[cid]["stage"]==s); tot.update(c)
    w(f"| {s} | {c['A']} | {c['B']} | {c['C']} | {sum(c.values())} |")
w(f"| All | {tot['A']} | {tot['B']} | {tot['C']} | {sum(tot.values())} |\n")
w("| Criterion | A | B | C |"); w("|---|---|---|---|")
crits=sorted({c["criterion"] for c in cells.values()}, key=lambda k: list(dict.fromkeys(c["criterion"] for c in cells.values())).index(k))
for cr in crits:
    c=Counter(V[cid]["class"] for cid in cells if cells[cid]["criterion"]==cr); w(f"| {cr} | {c['A']} | {c['B']} | {c['C']} |")
w("")
w(f"Reading: {tot['A']} of 120 cells ({100*tot['A']/120:.1f}%) can be settled by inspecting a published evaluation. {tot['B']} ({100*tot['B']/120:.1f}%) can only be settled by organisational records that no publication carries. {tot['C']} ({100*tot['C']/120:.1f}%) are judgements that no artefact settles. A completed matrix therefore contains {tot['B']+tot['C']} cells ({100*(tot['B']+tot['C'])/120:.1f}%) whose traffic-light colour is, to anyone outside the organisation, an assertion.\n")
w("## 2. Every cell, its class and what settles it\n")
w("Question text is quoted from the matrix under CC BY-NC 4.0 (Rincon and Chowdhury, Ada Lovelace Institute, 2026).\n")
for s in STAGES:
    w(f"### {s}\n"); w("| Cell | Criterion | Column | Class | Settled by | Question |"); w("|---|---|---|---|---|---|")
    for cid,c in cells.items():
        if c["stage"]!=s: continue
        v=V[cid]; w(f"| {cid} | {c['criterion']} | {c['column']} | {CL[v['class']]} | {', '.join(v['fields']) or ''} | {c['question']} |")
    w("")
w("## 3. The study set\n")
w(f"PubMed was queried on {sel['query'][:0]}{open('data/selection.json') and ''}the date recorded in `data/selection.json` with the query stored there. {sel['hits']} records were returned and {sel['screened']} screened. {sel['counts']['included_I1_I4']} met the four content criteria (primary evaluation, generative or fine-tuned LLM, title and abstract screening, a metric against a human reference); {sel['counts']['eligible_I1_I5']} of those also have open-access full text in PubMed Central. A random sample of {sel['sample']['size']} was drawn with seed {sel['sample']['seed']}. One further study was added by design because the Ada Lovelace Institute report alludes to it (GPT-4 across peer-reviewed and grey literature in multiple languages); its journal version is paywalled, so the arXiv version was used.\n")
w("| PMID | Year | Route | Study |"); w("|---|---|---|---|")
for pm,r in recs.items():
    s_=r["study"]; w(f"| {pm} | {s_.get('year','')} | {s_.get('selection_route','')} | {s_['title']} |")
w("")
if recs:
    w("## 4. Evidence present, per study and field\n")
    w("Statuses: present (P), partial (p), absent (.), not applicable (n). Locations and verbatim quotes are in `data/records/`.\n")
    pms=list(recs); w("| Field | "+" | ".join(pms)+" | present/"+str(len(pms))+" |"); w("|---|"+"---|"*(len(pms)+1))
    sym={"present":"P","partial":"p","absent":".","not_applicable":"n"}
    field_present=Counter()
    for f in F:
        row=[]
        for pm in pms:
            st=recs[pm]["evidence"][f]["status"]; row.append(sym[st]); field_present[f]+= st=="present"
        w(f"| {f} {F[f]['name']} | "+" | ".join(row)+f" | {field_present[f]} |")
    w("")
    w("## 5. Cell verdicts across the study set\n")
    w("An artefact-class cell counts as evidenced for a study only when every evidence field that settles it is present. These verdicts were computed set-based in Python and again by SHACL validation (pyshacl, and the open-ontologies engine where available); the script exits non-zero if the two disagree.\n")
    w("| Cell | Criterion | Settled by | Evidenced | Partially | Not evidenced |"); w("|---|---|---|---|---|---|")
    per_cell={}
    for cid in A:
        c=Counter(ver["verdicts"][pm][cid] for pm in pms); per_cell[cid]=c
        w(f"| {cid} | {cells[cid]['criterion']} | {', '.join(V[cid]['fields'])} | {c['evidenced']} | {c['partially_evidenced']} | {c['not_evidenced']} |")
    w("")
    per_study={pm:sum(1 for cid in A if ver["verdicts"][pm][cid]=="evidenced") for pm in pms}
    w("| PMID | Cells evidenced (of 39) | Partially | Not evidenced |"); w("|---|---|---|---|")
    for pm in pms:
        c=Counter(ver["verdicts"][pm][cid] for cid in A); w(f"| {pm} | {c['evidenced']} | {c['partially_evidenced']} | {c['not_evidenced']} |")
    vals=list(per_study.values())
    w("")
    never=[cid for cid in A if per_cell[cid]["evidenced"]==0]; always=[cid for cid in A if per_cell[cid]["evidenced"]==len(pms)]
    w("## 6. Headline numbers\n")
    w(f"- Studies in the set: {len(pms)} ({len([p for p in pms if recs[p]['study'].get('selection_route')=='sampled'])} sampled, {len([p for p in pms if recs[p]['study'].get('selection_route')=='report_referenced'])} report-referenced).")
    w(f"- Artefact-class cells fully evidenced per study: median {statistics.median(vals):g}, minimum {min(vals)}, maximum {max(vals)}, of 39.")
    w(f"- Cells no study in the set evidences: {len(never)} ({', '.join(never)}).")
    w(f"- Cells every study in the set evidences: {len(always)} ({', '.join(always) or 'none'}).")
    w(f"- Studies publishing the verbatim prompt (E18): {field_present['E18']} of {len(pms)}. Pinning an exact model version and date (E27): {field_present['E27']}. Reporting confidence intervals (E34): {field_present['E34']}. Reporting any subgroup breakdown (E08b): {field_present['E08b']}. Reporting performance by language or region (E08c): {field_present['E08c']}. Reporting energy or compute cost (E35): {field_present['E35']}.")
    w(f"- Pooled over the {len(pms)} studies and 39 cells, {sum(per_cell[c]['evidenced'] for c in A)} of {39*len(pms)} (study, cell) pairs are fully evidenced ({100*sum(per_cell[c]['evidenced'] for c in A)/(39*len(pms)):.1f}%).")
    w("")
open("REPORT.md","w").write("\n".join(L))
print("REPORT.md written", len(recs), "records")
